Remove obsolete conffile /etc/prads/init.d/prads.rc

diff --git a/debian/prads.postinst b/debian/prads.postinst
--- a/debian/prads.postinst
+++ b/debian/prads.postinst
@@ -1,21 +1,51 @@
 #!/bin/sh
-
-# Postinst script for prads.
-# Stig Sandbeck Mathisen <ssm@debian.org>
+# postinst script for #PACKAGE#
+#
+# see: dh_installdeb(1)
 
 set -e
-set -u
+
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <postinst> `abort-remove'
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
 
 setup_user() {
-    if ! getent passwd prads 2>&1 >/dev/null; then
-        adduser --quiet --system --no-create-home --group prads
-    fi
+	if ! getent passwd prads 2>&1 >/dev/null; then
+		adduser --quiet --system --no-create-home --group prads
+	fi
 }
 
-case ${1:-} in
-    configure)
-        setup_user
-        ;;
+
+case "$1" in
+	configure)
+		setup_user
+		dpkg-maintscript-helper rm_conffile /etc/prads/init.d/prads.rc 0.3.3-1~ prads -- "$@"
+		[ -d /etc/prads/init.d ] && rmdir --ignore-fail-on-non-empty /etc/prads/init.d
+
+		;;
+
+	abort-upgrade|abort-remove|abort-deconfigure)
+		dpkg-maintscript-helper rm_conffile /etc/prads/init.d/prads.rc 0.3.3-1~ prads -- "$@"
+
+		;;
+
+	*)
+		echo "postinst called with unknown argument \`$1'" >&2
+		exit 1
+		;;
 esac
 
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
+
 #DEBHELPER#
+
+exit 0
